name: SpigotBlankPlugin
main: com.htmlcomputer.plugin.SpigotPlugin
version: 1.0
api-version: 1.13
commands:
  kit:
    description: Your description
    usage: /<command>
    permission: yourplugin.yourcommandpermission 
  hi:
    description: Your description
    usage: /<command>
    permission: yourplugin.yourcommandpermission 
  hello:
    description: Your description
    usage: /<command>
    permission: yourplugin.yourcommandpermission 